lwp/views/auth.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function

import time

from flask import Blueprint, request, session, redirect, url_for, render_template, flash

from lwp.utils import query_db, hash_passwd, get_token, config

# TODO: see if we can move this block somewhere better
try:
    AUTH = config.get('global', 'auth')
    print(' * Auth type: ' + AUTH)
    if AUTH == 'ldap':
        import ldap
        LDAP_HOST = config.get('ldap', 'host')
        LDAP_PORT = int(config.get('ldap', 'port'))
        LDAP_BASE = config.get('ldap', 'base')
        LDAP_BIND_DN = config.get('ldap', 'bind_dn')
        LDAP_PASS = config.get('ldap', 'password')
        ID_MAPPING = config.get('ldap', 'id_mapping')
        DISPLAY_MAPPING = config.get('ldap', 'display_mapping')
        OBJECT_CLASS = config.get('ldap', 'object_class')
    elif AUTH == 'htpasswd':
        HTPASSWD_FILE = config.get('htpasswd', 'file')
except NameError as err:
    print(' ! Revert to DB authentication ' + str(err))
    AUTH = 'database'



# Flask module
mod = Blueprint('auth', __name__)


@mod.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        request_username = request.form['username']
        request_passwd = request.form['password']

        current_url = request.form['url']

        if AUTH == 'ldap':
            try:
                l = ldap.initialize('ldap://%s:%d' % (LDAP_HOST, LDAP_PORT))
                l.set_option(ldap.OPT_REFERRALS, 0)
                l.protocol_version = 3
                l.simple_bind(LDAP_BIND_DN, LDAP_PASS)
                q = l.search_s(LDAP_BASE, ldap.SCOPE_SUBTREE, '(&(objectClass=' + OBJECT_CLASS + ')(' + ID_MAPPING + '=' + request_username + '))', [])[0]
                l.bind_s(q[0], request_passwd, ldap.AUTH_SIMPLE)
                #set the parameters for user by ldap objectClass
                user = {
                    'username': q[1][ID_MAPPING][0].decode('utf8'),
                    'name': q[1][DISPLAY_MAPPING][0].decode('utf8'),
                    'su': 'Yes'
                }
            except Exception, e:
                print(str(e))
                user = None
        elif AUTH == 'htpasswd':
            from lwp.utils import check_htpasswd
            user = None
            if check_htpasswd(HTPASSWD_FILE, request_username, request_passwd):
                user = {
                    'username': request_username,
                    'name': request_username,
                    'su': 'Yes'
                }
        else:
            request_passwd = hash_passwd(request_passwd)
            user = query_db('select name, username, su from users where username=? and password=?', [request_username, request_passwd], one=True)

        if user:
            session['logged_in'] = True
            session['token'] = get_token()
            session['last_activity'] = int(time.time())
            session['username'] = user['username']
            session['name'] = user['name']
            session['su'] = user['su']
            flash(u'You are logged in!', 'success')

            if current_url == url_for('auth.login'):
                return redirect(url_for('main.home'))
            return redirect(current_url)

        flash(u'Invalid username or password!', 'error')
    return render_template('login.html', auth=AUTH)


@mod.route('/logout')
def logout():
    session.pop('logged_in', None)
    session.pop('token', None)
    session.pop('last_activity', None)
    session.pop('username', None)
    session.pop('name', None)
    session.pop('su', None)
    flash(u'You are logged out!', 'success')
    return redirect(url_for('auth.login'))

lwp/views/main.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function
import os
import re
import time
import socket
import subprocess
import ConfigParser

from flask import Blueprint, request, session, g, redirect, url_for, abort, render_template, flash, jsonify

import lwp
import lwp.lxclite as lxc
from lwp.utils import query_db, if_logged_in, get_bucket_token, hash_passwd, config, cgroup_ext
from lwp.views.auth import AUTH

# TODO: see if we can move this block somewhere better
try:
    USE_BUCKET = config.getboolean('global', 'buckets')
    BUCKET_HOST = config.get('buckets', 'buckets_host')
    BUCKET_PORT = config.get('buckets', 'buckets_port')
except ConfigParser.NoOptionError:
    USE_BUCKET = False
    print("- Bucket feature disabled")


storage_repos = config.items('storage_repository')

# Flask module
mod = Blueprint('main', __name__)


@mod.route('/')
@mod.route('/home')
@if_logged_in()
def home():
    """
    home page function
    """
    listx = lxc.listx()
    containers_all = []

    for status in ('RUNNING', 'FROZEN', 'STOPPED'):
        containers_by_status = []

        for container in listx[status]:
            container_info = {
                'name': container,
                'settings': lwp.get_container_settings(container, status),
                'memusg': 0,
                'bucket': get_bucket_token(container)
            }

            containers_by_status.append(container_info)
        containers_all.append({
            'status': status.lower(),
            'containers': containers_by_status
        })

    return render_template('index.html', containers=lxc.ls(), containers_all=containers_all, dist=lwp.check_ubuntu(),
                           host=socket.gethostname(), templates=lwp.get_templates_list(), storage_repos=storage_repos,
                           auth=AUTH)


@mod.route('/about')
@if_logged_in()
def about():
    """
    about page
    """
    return render_template('about.html', containers=lxc.ls(), version=lwp.check_version())


@mod.route('/<container>/edit', methods=['POST', 'GET'])
@if_logged_in()
def edit(container=None):
    """
    edit containers page and actions if form post request
    """
    host_memory = lwp.host_memory_usage()
    cfg = lwp.get_container_settings(container)

    if request.method == 'POST':
        form = request.form.copy()

        if form['bucket'] != get_bucket_token(container):
            g.db.execute("INSERT INTO machine(machine_name, bucket_token) VALUES (?, ?)", [container, form['bucket']])
            g.db.commit()
            flash(u'Bucket config for %s saved' % container, 'success')

        #convert boolean in correct value for lxc, if checkbox is inset value is not submitted inside POST
        form['flags'] = 'up' if 'flags' in form else 'down'
        form['start_auto'] = '1' if 'start_auto' in form else '0'

        # if memlimits/memswlimit is at max values unset form values
        if int(form['memlimit']) == host_memory['total']:
            form['memlimit'] = ''
        if int(form['swlimit']) == host_memory['total'] * 2:
            form['swlimit'] = ''

        for option in form.keys():
            #if the key is supported AND is different
            if option in cfg.keys() and form[option] != cfg[option]:
                # validate value with regex
                if re.match(cgroup_ext[option][1], form[option]):
                    lwp.push_config_value(cgroup_ext[option][0], form[option], container=container)
                    flash(cgroup_ext[option][2], 'success')
                else:
                    flash('Cannot validate value for option {}. Unsaved!'.format(option), 'error')

        # we should re-read container configuration now to be coherent with the newly saved values
        cfg = lwp.get_container_settings(container)

    info = lxc.info(container)
    infos = {'status': info['state'], 'pid': info['pid'], 'memusg': lwp.memory_usage(container)}

    return render_template('edit.html', containers=lxc.ls(), container=container, infos=infos, settings=cfg, host_memory=host_memory, storage_repos=storage_repos)


@mod.route('/settings/lxc-net', methods=['POST', 'GET'])
@if_logged_in()
def lxc_net():
    """
    lxc-net (/etc/default/lxc) settings page and actions if form post request
    """
    if session['su'] != 'Yes':
        return abort(403)

    if request.method == 'POST':
        if lxc.running() == []:
            cfg = lwp.get_net_settings()
            ip_regex = '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'

            form = {}
            for key in ['bridge', 'address', 'netmask', 'network', 'range', 'max']:
                form[key] = request.form.get(key, None)
            form['use'] = request.form.get('use', None)

            if form['use'] != cfg['use']:
                lwp.push_net_value('USE_LXC_BRIDGE', 'true' if form['use'] else 'false')

            if form['bridge'] and form['bridge'] != cfg['bridge'] and \
                    re.match('^[a-zA-Z0-9_-]+$', form['bridge']):
                lwp.push_net_value('LXC_BRIDGE', form['bridge'])

            if form['address'] and form['address'] != cfg['address'] and \
                    re.match('^%s$' % ip_regex, form['address']):
                lwp.push_net_value('LXC_ADDR', form['address'])

            if form['netmask'] and form['netmask'] != cfg['netmask'] and \
                    re.match('^%s$' % ip_regex, form['netmask']):
                lwp.push_net_value('LXC_NETMASK', form['netmask'])

            if form['network'] and form['network'] != cfg['network'] and \
                    re.match('^%s(?:/\d{1,2}|)$' % ip_regex, form['network']):
                lwp.push_net_value('LXC_NETWORK', form['network'])

            if form['range'] and form['range'] != cfg['range'] and \
                    re.match('^%s,%s$' % (ip_regex, ip_regex), form['range']):
                lwp.push_net_value('LXC_DHCP_RANGE', form['range'])

            if form['max'] and form['max'] != cfg['max'] and \
                    re.match('^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$', form['max']):
                lwp.push_net_value('LXC_DHCP_MAX', form['max'])

            if lwp.net_restart() == 0:
                flash(u'LXC Network settings applied successfully!', 'success')
            else:
                flash(u'Failed to restart LXC networking.', 'error')
        else:
            flash(u'Stop all containers before restart lxc-net.', 'warning')
    return render_template('lxc-net.html', containers=lxc.ls(), cfg=lwp.get_net_settings(), running=lxc.running())


@mod.route('/lwp/users', methods=['POST', 'GET'])
@if_logged_in()
def lwp_users():
    """
    returns users and get posts request : can edit or add user in page.
    this funtction uses sqlite3
    """
    if session['su'] != 'Yes':
        return abort(403)

    if AUTH == 'ldap':
        return abort(403, 'You are using ldap as AUTH backend.')

    if AUTH == 'htpasswd':
        return abort(403, 'You are using htpasswd as AUTH backend.')

    try:
        trash = request.args.get('trash')
    except KeyError:
        trash = 0

    su_users = query_db("SELECT COUNT(id) as num FROM users WHERE su='Yes'", [], one=True)

    if request.args.get('token') == session.get('token') and int(trash) == 1 and request.args.get('userid') and \
            request.args.get('username'):
        nb_users = query_db("SELECT COUNT(id) as num FROM users", [], one=True)

        if nb_users['num'] > 1:
            if su_users['num'] <= 1:
                su_user = query_db("SELECT username FROM users WHERE su='Yes'", [], one=True)

                if su_user['username'] == request.args.get('username'):
                    flash(u'Can\'t delete the last admin user : %s' % request.args.get('username'), 'error')
                    return redirect(url_for('main.lwp_users'))

            g.db.execute("DELETE FROM users WHERE id=? AND username=?", [request.args.get('userid'),
                                                                         request.args.get('username')])
            g.db.commit()
            flash(u'Deleted %s' % request.args.get('username'), 'success')
            return redirect(url_for('main.lwp_users'))

        flash(u'Can\'t delete the last user!', 'error')
        return redirect(url_for('main.lwp_users'))

    if request.method == 'POST':
        users = query_db('SELECT id, name, username, su FROM users ORDER BY id ASC')

        if request.form['newUser'] == 'True':
            if not request.form['username'] in [user['username'] for user in users]:
                if re.match('^\w+$', request.form['username']) and request.form['password1']:
                    if request.form['password1'] == request.form['password2']:
                        if request.form['name']:
                            if re.match('[a-z A-Z0-9]{3,32}', request.form['name']):
                                g.db.execute("INSERT INTO users (name, username, password) VALUES (?, ?, ?)",
                                             [request.form['name'], request.form['username'],
                                              hash_passwd(request.form['password1'])])
                                g.db.commit()
                            else:
                                flash(u'Invalid name!', 'error')
                        else:
                            g.db.execute("INSERT INTO users (username, password) VALUES (?, ?)",
                                         [request.form['username'], hash_passwd(request.form['password1'])])
                            g.db.commit()

                        flash(u'Created %s' % request.form['username'], 'success')
                    else:
                        flash(u'No password match', 'error')
                else:
                    flash(u'Invalid username or password!', 'error')
            else:

lwp/templates/includes/aside.html
<div class="span3 hidden-phone">
    <div class="well sidebar-nav">
        <ul class="nav nav-list">
            <li class="nav-header">General</li>
            <li{% if request.path=="/" or request.path=="/home" %} class="active"{% endif %}><a href="{{ url_for('main.home') }}" id="home-btn"><i class="icon-home"></i> Overview<i class="icon-refresh hide" id="home-load" style="float:right;margin-top:3px;"></i></a></li>
        </ul>
        {% if containers != [] %}
        <ul class="nav nav-list">
            <li class="nav-header">Containers</li>
            {% for c in containers %}
            <li{% if request.path=='/'+ c +'/edit' %} class="active"{% endif %}><a href="{{ url_for('main.edit',container=c) }}"><i class="icon-hdd"></i> {{c}}</a></li>
            {% endfor %}
        </ul>{% endif %}
        {% if session.su == 'Yes' %}
        <ul class="nav nav-list">
            <li class="nav-header">LXC Settings</li>
            <li{% if request.path=="/settings/lxc-net" %} class="active"{% endif %}><a href="{{ url_for('main.lxc_net') }}"><i class="icon-globe"></i> Networking</a></li>
            <li{% if request.path=="/lwp/tokens" %} class="active"{% endif %}><a href="{{ url_for('main.lwp_tokens') }}"><i class="icon-lock"></i> API tokens</a></li>
            <li{% if request.path=="/checkconfig" %} class="active"{% endif %}><a href="{{ url_for('main.checkconfig') }}"><i class="icon-check"></i> Check config</a></li>
        </ul>{% endif %}
        <ul class="nav nav-list">
            <li class="nav-header">LXC Web Panel</li>
            {% if session.su == 'Yes' and auth != 'ldap' %}
            <li{% if request.path=="/lwp/users" %} class="active"{% endif %}><a href="{{ url_for('main.lwp_users') }}"><i class="icon-user"></i> Users</a></li>
            {% endif %}
            <li{% if request.path=="/about" %} class="active"{% endif %}><a href="{{ url_for('main.about') }}"><i class="icon-info-sign"></i> About</a></li>
        </ul>
    </div>
</div>

lwp/templates/includes/modal_backup.html
<div id="backupCT" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="cloneCTLabel" aria-hidden="true">
    <form method="post" action="{{ url_for('main.backup_container') }}" style="margin:0;">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="cloneCTLabel">Backup container</h3>
        </div>
        <div class="modal-body">
            <div class="control-group">
                <div class="controls input-prepend">
                    <span class="add-on"><i class="icon-download-alt"></i></span>
                    <select id="selectContainer" name="orig">
                        {% for c in containers %}
                        {% if c == container %}
                        <option value="{{ c }}" selected>{{c}}</option>
                        {% else %}
                        <option value="{{ c }}">{{c}}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>

                <div class="controls input-prepend pull-right">
                    <span class="add-on"><i class="icon-hdd"></i></span>
                    <select id="selectSR" name="dest">
                        {% for sr in storage_repos %}<option value="{{ sr[0] }}">{{sr[0]}}</option>{% endfor %}
                    </select>
                </div>
                <p><strong>Beware:</strong> container will be frozen if in 'running' state.</p>
                <p><strong>Note:</strong> Push option use <a href="http://claudyus.github.io/file-bucket/">file-bucket</a> to backup instances remotely.</p>

            </div>
        </div>

        <div class="modal-footer">
            <div class="buttons-modal-footer">
                <div class="switch pull-left" data-on-label="<small>Push</small>" data-off-label="<small>No push</small>" data-on="success" data-off="primary">
                    <input type="checkbox" name="push" value="False" />
                </div>
                <button class="btn btn-small" data-dismiss="modal" aria-hidden="true">Close</button>
                <button type="submit" class="btn btn-primary modalbutton">Backup</button>
            </div>
            <div class="loader-modal-footer hide">
                <div class="progress progress-striped active">
                    <div class="bar" style="width: 100%;"></div>
                </div>
            </div>
        </div>
    </form>
</div>

lwp/templates/includes/modal_clone.html
<div id="cloneCT" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="cloneCTLabel" aria-hidden="true">
    <form method="post" action="{{ url_for('main.clone_container') }}" style="margin:0;">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="cloneCTLabel">Clone container</h3>
        </div>
        <div class="modal-body">
            <div class="control-group">
                <div class="controls input-prepend">
                    <span class="add-on"><i class="icon-download-alt"></i></span>
                    <select id="selectContainer" name="orig">
                        {% for c in containers %}
                        {% if c == container %}
                        <option value="{{ c }}" selected>{{c}}</option>
                        {% else %}
                        <option value="{{ c }}">{{c}}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>

                <div class="controls input-prepend pull-right">
                    <span class="add-on"><i class="icon-folder-open"></i></span>
                    <input id="inputName" type="text" pattern="(?!^containers$)[a-zA-Z0-9_-]+" placeholder="Clone name" name="name">
                </div>

            </div>
        </div>

        <div class="modal-footer">
            <div class="buttons-modal-footer">
                <div class="switch pull-left" data-on-label="<small>Snapshot</small>" data-off-label="<small>&nbsp;&nbsp;&nbsp;Classic&nbsp;&nbsp;&nbsp;</small>" data-on="success" data-off="primary">
                    <input type="checkbox" name="snapshot" value="True" />
                </div>
                <button class="btn btn-small" data-dismiss="modal" aria-hidden="true">Close</button>
                <button type="submit" class="btn btn-inverse modalbutton">Clone</button>
            </div>
            <div class="loader-modal-footer hide">
                <div class="progress progress-striped active">
                    <div class="bar" style="width: 100%;"></div>
                </div>
            </div>
        </div>
    </form>
</div>

lwp/templates/includes/modal_create.html
<div id="createCT" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="createCTLabel" aria-hidden="true">
    <form method="post" action="{{ url_for('main.create_container') }}">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="createCTLabel">Create container</h3>
        </div>
        <div class="modal-body">
            <div class="control-group">
                <div class="controls input-prepend">
                    <span class="add-on"><i class="icon-folder-open"></i></span>
                    <input id="inputName" type="text" pattern="(?!^containers$)[a-zA-Z0-9_-]+" placeholder="Name" name="name">
                </div>

                <div class="controls input-prepend pull-right">
                    <span class="add-on"><i class="icon-download-alt"></i></span>
                    <select id="selectTemplate" name="template">
                        {% for template in templates %}<option value="{{ template }}" {% if template == 'ubuntu' %}selected{% endif %}>{{ template }}</option>{% endfor %}
                    </select>
                </div>
            </div>
            <button id ="advancedcreate" class="btn btn-small">Advanced options</button>
            <div id="advancedcreatediv" class="advanced-wrapper hide">
                <br />
                <div class="control-group pull-right">
                    <label class="control-label" for="inputCommand">LXC Container configuration</label>
                    <div class="controls input-prepend">
                        <span class="add-on"><i class="icon-wrench"></i></span>
                        <input type="text" id="inputCommand" name="command" placeholder="Container command">
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls input-prepend">
                        <label class="control-label" for="backingstorecreate">Backing store*</label>
                        <span class="add-on"><i class="icon-hdd"></i></span>
                        <select id="backingstorecreate" class="backingstore" name="backingstore">
                            <option value="default" selected>Default</option>
                            <option value="directory">Directory</option>
                            <option value="lvm">LVM</option>
                            <option value="zfs">ZFS</option>
                        </select>
                    </div>
                    <span class="help-inline"><small>*By default it is 'none', which is a simple directory tree under /var/lib/lxc/&lt;name&gt;/rootfs</small></span>
                </div>
                <div class="control-group hide directory">
                    <label class="control-label" for="inputDirectory">Directory</label>
                    <div class="controls input-prepend">
                        <span class="add-on"><i class="icon-folder-close"></i></span>
                        <input type="text" id="inputDirectory" name="dir" placeholder="Directory">
                    </div>
                </div>
                <div class="control-group hide lvm">
                    <div class="controls">
                        <label class="control-label" for="inputLV">LV Name</label>
                        <input type="text" id="inputLV" name="lvname" placeholder="LV Name">
                        <label class="control-label" for="inputVG">VG Name</label>
                        <input type="text" id="inputVG" name="vgname" placeholder="VG Name">
                        <label class="control-label" for="inputFS">File system</label>
                        <input type="text" id="inputFS" name="fstype" placeholder="ext4">
                        <label class="control-label" for="inputFSSize">Size</label>
                        <input type="text" id="inputFSSize" name="fssize" placeholder="500M">
                    </div>
                </div>
                <div class="control-group hide zfs">
                    <div class="controls">
                        <label class="control-label" for="inputZFS">zpool Name</label>
                        <input type="text" id="inputZFS" name="zpoolname" placeholder="lxc">
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <div class="buttons-modal-footer">
                <button class="btn btn-small" data-dismiss="modal" aria-hidden="true">Close</button>
                <button type="submit" class="btn btn-success modalbutton"><i class="icon-plus-sign icon-white"></i> Create</button>
            </div>
            <div class="loader-modal-footer hide">
                <div class="progress progress-striped active">
                    <div class="bar" style="width: 100%;"></div>
                </div>
                <p class="text-center">This could take a while...</p>
            </div>
        </div>
    </form>
</div>

lwp/templates/includes/modal_delete.html
<div id="delete" class="modal hide fade" role="dialog" aria-labelledby="deleteLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="deleteLabel" class="text-error">Oh wait!</h3>
    </div>
    <div class="modal-body">
        <strong>Are you sure you want to delete this user ?</strong>
    </div>
    <div class="modal-footer">
        <div class="buttons-modal-footer">
            <button class="btn btn-small" data-dismiss="modal" aria-hidden="true">Cancel</button>
            <a class="btn btn-danger delete-link modalbutton" href=""><i class="icon-trash icon-white"></i> Destroy</a>
        </div>
        <div class="progress progress-striped active hide loader-modal-footer">
            <div class="bar" style="width: 100%;"></div>
        </div>
    </div>
</div>

lwp/templates/includes/modal_destroy.html
<div id="destroy" class="modal hide fade" role="dialog" aria-labelledby="destroyLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="destroyLabel" class="text-error">Oh wait!</h3>
    </div>
    <div class="modal-body">
        <strong>Are you sure you want to destroy '<span id="destroy-container-name"></span>' ?</strong>
    </div>
    <div class="modal-footer">
        <div class="buttons-modal-footer">
            <button class="btn btn-small" data-dismiss="modal" aria-hidden="true">Cancel</button>
            <a class="btn btn-danger destroy-link modalbutton" href=""><i class="icon-trash icon-white"></i> Destroy</a>
        </div>
        <div class="progress progress-striped active hide loader-modal-footer">
            <div class="bar" style="width: 100%;"></div>
        </div>
    </div>
</div>

lwp/templates/includes/modal_reboot.html
<div id="reboot" class="modal hide fade" role="dialog" aria-labelledby="rebootLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="rebootLabel" class="text-error">Oh wait!</h3>
    </div>
    <div class="modal-body">
        <strong>Reboot this system now ?</strong>
    </div>
    <div class="modal-footer">
        <button class="btn btn-small" data-dismiss="modal" aria-hidden="true">Cancel</button>
        <a class="btn btn-danger" href="{{ url_for('main.action', name='host', action='main.reboot', token=session.token) }}"><i class="icon-off icon-white"></i> Reboot</a>
    </div>
</div>

lwp/templates/includes/nav.html
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="{{ url_for('main.home') }}">LXC Web Panel</a>
            <div class="nav-collapse collapse">
                <ul class="nav visible-phone">
                    {% if containers != [] %}
                    <li class="divider"></li>
                    <li class="nav-header">Containers</li>
                    {% for c in containers %}
                    <li{% if request.path=='/'+ c +'/edit' %} class="active"{% endif %}><a href="{{ url_for('main.edit',container=c) }}"><i class="icon-hdd icon-white"></i> {{c}}</a></li>
                    {% endfor %}
                    {% endif %}
                    {% if session.su == 'Yes' %}
                    <li class="divider"></li>
                    <li class="nav-header">LXC Settings</li>
                    <li{% if request.path=="/settings/lxc-net" %} class="active"{% endif %}><a href="{{ url_for('main.lxc_net') }}"><i class="icon-globe icon-white"></i> Networking</a></li>
                    <li{% if request.path=="/lwp/tokens" %} class="active"{% endif %}><a href="{{ url_for('main.lwp_tokens') }}"><i class="icon-lock icon-white"></i> API tokens</a></li>
                    <li{% if request.path=="/checkconfig" %} class="active"{% endif %}><a href="{{ url_for('main.checkconfig') }}"><i class="icon-check icon-white"></i> Check config</a></li>
                    {% endif %}
                    <li class="divider"></li>
                    <li class="nav-header">Users action</li>
                    <li><a href="{{ url_for('main.lwp_users') }}"><i class="icon-user icon-white"></i> Users</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">Logout ({% if session.name and session.name != 'None' %}{{ session.name }}{% else %}{{ session.username }}{% endif %})</a></li>
                </ul>
                <p class="navbar-text pull-right hidden-phone">
                    <a href="{{ url_for('auth.logout') }}" class="navbar-link">Logout ({% if session.name and session.name != 'None' %}{{ session.name }}{% else %}{{ session.username }}{% endif %})</a>
                </p>
            </div>
        </div>
    </div>
</div>